version: "3.1"

services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  registry-server:
    image: leoyassuda/registry-spring-boot
    container_name: registry-server
    ports:
      - 8761:8761
