spring:
  profiles:
    active: local
  application:
    name: product-service
  main:
    banner-mode: "off"
  security:
    user:
      name: user
      password: password
server:
  port: 8087
info:
  app:
    name: Product Service
    description: Simple Rest Service of products
    version: @project.version@
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
    jmx:
      exposure:
        include: health,info,metrics,shutdown
---
spring:
  profiles: local
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb;ignorecase=true;mv_store=false;mvcc=false
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  devtools:
    livereload:
      enabled: true
---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: user
      password: password
---
spring:
  profiles: cloud