server:
  port: 8181
spring:
  application:
    name: "product-service"
  main:
    banner-mode: "off"
  data:
    mongodb:
      database: "product-service"
# swagger-ui custom path
springdoc:
  swagger-ui.path: /swagger-ui.html
mongo:
  databaseName: "product-service"
---
